//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtoCommerce.B2BExtensionsModule.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class B2BExtensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal B2BExtensionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtoCommerce.B2BExtensionsModule.Web.Resources.B2BExtensionsResources", typeof(B2BExtensionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{message}} &amp;gt;br&amp;lt; You have been invited to register in {{store_name}} as {{company_name}} company member. &amp;gt;br&amp;lt; Go to &amp;lt;strong&amp;gt;&amp;lt;a href=&quot;{{ url }}&quot;&amp;gt;this page&amp;lt;/a&amp;gt;&amp;lt;/strong&amp;gt to create your account. &amp;gt;br&amp;lt; If you are unable to to click on the link above, simple copy the link and paste into the browser where you enter web addresses and press enter. &amp;gt;br&amp;lt; If you have any questions, please contact your company&apos;s account administrator, {{admin.full_name}} at {{admin.email}}..
        /// </summary>
        internal static string InviteEmailNotificationBody {
            get {
                return ResourceManager.GetString("InviteEmailNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to join {{company_name}}..
        /// </summary>
        internal static string InviteEmailNotificationSubject {
            get {
                return ResourceManager.GetString("InviteEmailNotificationSubject", resourceCulture);
            }
        }
    }
}
